apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::152156235619:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1ULRVZCNTOJ9H
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::152156235619:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-24T00:11:31Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1665"
  uid: 9b704929-bfc6-468e-b4dc-f6d2b6f4b69f
